description: >
  Install docker-compose.

steps:
  - install-gh-release:
      binary-name: docker-compose
      url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64
      checksum: bcfd9ea51dee4c19dccdfaeef0e7956ef68bf14f3d175933742061a7271ef0f5
